# Background and summary of results {#summary}

outline: 

- DA analysis
  + abundance: absolute abundance e.g. cell density; relative abundance (e.g. proportions, ratios); other transformations are commonly used, but we focus on these b/c.
    - absolute abundance is more directly connected to ecological processes affecting the microbe and the host and thus may be more informative for host and environmental impact.
  + (log) fold changes: Microbiome DA most often done on the log scale (b/c different organisms might have vastly different average densities, and because of the connection with the multiplicative growth process underlying ecological dynamics). DA analysis is not interested in the average abundance differences in organisms, but in the changes - hence the focus elsewhere and here on log fold changes (LFCs) of a taxon across samples.
  + (linear) regression; intercepts and slopes: (take )
- error in DA analysis
  + generally not interested in the average abudnance, but in the change across conditions; this means the LFC for pair of samples or the slope in the regression model.
  + hope that the effect of bias absorbed in the intercept, leaving the slope estimate unaffected.
- consistent vs inconsistent multiplicative (or fold) error
  + for accurate FCs
    - need consistent multiplicative (or fold) error; then the error cancels in the FC.
    - inconsistent FC, does not; this can lead to sign errors (estimating a positive LFC when truly negative, or vice versa) or magnitude errors (estimating an LFC with the correct sign but a larger or smaller absolute value than the true value)
  + for accurate regression slopes
    - b/c analyzing many samples, a randomly varying error serves to add noise without affecting the expected slope - leads to noisier and less precise slope estimates.
    - correlation of error with covariate leads to statistical bias (systematic error) in the slope estimate, leading to magnitude or sign errors in the slope estimate
- HERE HERE
- relative vs. absolute abundance
- ratios vs. proportions
- sample mean efficiency
- reference taxa
- todo: illustrate these ideas with a schematic figure

clarifications:
- Microbiome scientists are generally not really after absolute abundance in the sense of an absolute number of cells. By "absolute abundance" they generally mean abundance relative to some non-taxonomic property, such as the total volume or (wet or dry) mass of the sample.
  - Write this here for now, but might want to make a footnote.

thoughts

- use of models; (perhaps introduce role of models in measurement? or leave for next section)
- define scope to all current AA methods; distinguish based on how affected by bias and other concerns like non-linear extraction, and suggest a new approach that is less affected by bias
    - Note that there are a variety of AA methods which make different assumptions about MGS and are differently interact with bias; we survey/taxonomize/synthesize them
- might include computational methods in scope, and use the term "calibration"; and ref to the future appendix that surveys the various methods
- need to think more about the first sentence
- Might want to hear mention the ratio and proportion divide
